Update feast doc, fix issue
elements-of-ai/kubeflow-docs pull request #39
Opened 2023-03-23 11:24 UTC by AmyHoney

2023-03-23 11:25 UTC, AmyHoney commented
Fix issue: TypeError: cannot create weak reference to 'property' object

2023-03-24 05:09 UTC, skolavmware commented on docs/user-guide/feast.rst
> +You need to use your MinIO parameters obtained befor to update the MinIO parameters, create a bucket for feast and upload data files to bucket.
Small typo - before

2023-03-24 05:15 UTC, skolavmware commented on docs/user-guide/feast.rst
We can also add - apt-get install wget,  as we are using wget in below lines

2023-03-24 05:18 UTC, skolavmware commented on docs/user-guide/feast.rst
> +New a python file to write **data_sources.py** file to load data from S3 storage
Its always better to tell where to copy these python files, is it on kubeflow notebook or terminal

2023-03-24 05:27 UTC, skolavmware requested changes
Small changes requested

2023-03-24 06:47 UTC, AmyHoney commented on docs/user-guide/feast.rst
Thanks Srinivas. `wget` has installed in these kubeflow Docker Images. Thus, there is no necessary to install wget manually.

2023-03-24 07:04 UTC, skolavmware commented on docs/user-guide/feast.rst
right but when we testing this on the nimbus VM we need to install it explicitly

2023-03-25 10:12 UTC, liuqi approved these changes

2023-03-25 10:12 UTC, merged